@startmindmap
top to bottom direction
* 企业大模型知识库框架
** 文档处理
*** 文档清洗
*** 跨平台文件转换
*** 文件对象化转录(Markdown转录)
*** 文件向量化(大语言模型摘要及向量化)
** 文档建模(文件模型抽象)
*** 文件系统树
*** 内容对象树
*** 语义树
*** 版本树
** 应用框架搭建
*** 数据库搭建
**** 内容对象数据库
**** 向量数据库
*** HMI前端（Streamlit, Gradio）
*** RAG框架集成
*** 模型上下文协议(MCP)
*** 智能体(Agent)
** 检索增强生成(RAG)
*** 基于文本相似度检索(内嵌向量)
*** 基于搜索算法检索
@endmindmap