
@startmindmap
top to bottom direction
* 测试
      * 模块
            * 传感器
                  * 导航
                  * 关节
            * 人机交互
      * 功能
            * 导航 
                  * 里程计
                  * 轨迹生成
                  * 地图
                  * 物体识别
            * 行走
                  * 步态控制
                  * 关节运动规划
                  * 关节运动追踪
            * 手臂控制  
                  * 关节运动规划
                  * 关节运动追踪
            * 末端工具
                  * 夹手控制

      * 可靠性
            * 安全
                  * 机械
                  * 电气
                  * 软件
                  * 人机交互
            * 应急响应
            * 环境适应性
                  * 电磁兼容性
@endmindmap